// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Shim from "use-sync-external-store/shim";
import * as WithSelector from "use-sync-external-store/shim/withSelector";

var value = {
  contents: 1
};

function subscribe(cb) {
  console.log("subscribing...");
  var timer = setInterval((function (param) {
          value.contents = value.contents + 1 | 0;
          Curry._1(cb, undefined);
        }), 1000);
  return function (param) {
    console.log("unsubscribing...");
    clearInterval(timer);
  };
}

function getSnapshot(param) {
  return value;
}

function SyncExternalStore_test(Props) {
  var valueA = Shim.useSyncExternalStore(subscribe, getSnapshot, undefined);
  var valueB = WithSelector.useSyncExternalStoreWithSelector(subscribe, getSnapshot, undefined, (function (ref) {
          return ref.contents;
        }), (function (a, b) {
          return a === b;
        }));
  return React.createElement("div", undefined, React.createElement("span", undefined, valueA.contents), React.createElement("span", undefined, valueB));
}

var make = SyncExternalStore_test;

export {
  value ,
  subscribe ,
  getSnapshot ,
  make ,
}
/* react Not a pure module */
